image: 
  name: gcr.io/xm-cloudbuild/cb-nightwatch-automation:latest
  username: _json_key
  password: '$GCR_JSON_KEY'

options:
  docker: true

definitions:
  steps:
    - step: &build-image
        name: Build Docker image
        script:
          - echo $GCR_JSON_KEY | docker login -u _json_key --password-stdin https://gcr.io
          - docker build -t gcr.io/xm-cloudbuild/cb-nightwatch-automation:latest -f Dockerfile .
          - docker push gcr.io/xm-cloudbuild/cb-nightwatch-automation:latest
    - step: &install
        name: 'INSTALL'
        caches:
          - node
        script:
          - npm install
        artifacts:
          - node_modules/**
    - step: &lint
        name: 'LINT'
        script:
          - npm run lint
    - step: &test
        name: 'TEST'
        script:
          - npm run test:smoke

pipelines:
  default:
    - step: *build-image
    - step: *install
    - step: *lint
    - step: *test